#!/usr/bin/env python3
"""
Practical example of running bicycle route optimization
with the Dutch network data generated by create_dataset.py
"""

import sys
import os
import json
import numpy as np
import matplotlib.pyplot as plt
from problem import run_optimization, analyze_results, BicycleRoutingProblem, create_result_comparison_plot


def main():
    """
    Complete example workflow for bicycle route optimization
    """
    print("🚴‍♂️ Dutch Bicycle Route Multi-Objective Optimization")
    print("=" * 60)

    # Step 1: Check if real data exists, otherwise create demo
    data_file = "real_dutch_bike_network_pygmo.json"

    if not os.path.exists(data_file):
        print(f"⚠️  Real network data '{data_file}' not found.")
        print("📝 First run: python create_dataset.py")
        print("🔄 Creating synthetic demo data instead...")
        data_file = create_demo_data()
    else:
        print(f"✅ Using real Dutch network data: {data_file}")

    # Step 2: Load and inspect data
    inspect_network_data(data_file)

    # Step 3: Run single consistent scenario for meaningful analysis
    print(f"\n🎯 Running bicycle route optimization...")

    try:
        # Check if target cities exist and are reachable before optimization
        with open(data_file, 'r') as f:
            data = json.load(f)

        available_cities = data.get('cities', list(data.get('city_coordinates', {}).keys()))

        # Single consistent scenario for analysis
        scenario = {
            "name": "Netherlands Multi-City Tour",
            "start": "Leiden",
            "targets": ["Amsterdam", "Utrecht", "Eindhoven"],
            "algorithm": "nsga2"
        }

        # Validate cities exist
        invalid_cities = [city for city in [scenario["start"]] + scenario["targets"]
                          if city not in available_cities]

        if invalid_cities:
            print(f"❌ Invalid cities in scenario: {invalid_cities}")
            print(f"   Available cities: {available_cities}")
            return

        print(f"🚴‍♂️ Scenario: {scenario['name']}")
        print(f"   Start: {scenario['start']}")
        print(f"   Targets: {scenario['targets']}")

        results = run_optimization(
            data_file=data_file,
            start_city=scenario["start"],
            target_cities=scenario["targets"],
            algorithm=scenario["algorithm"],
            population_size=128,
            generations=20,
            max_route_length=10,
            comfort_constraints={'safety': 2.0, 'slope': 2.0},
            comfort_objectives=['scenic', 'roughness'],
            use_penalty_method=True
        )

        print(f"✅ Completed: {len(results['pareto_front_indices'])} Pareto-optimal solutions found")

        # Detailed analysis
        print(f"\n📊 Detailed Analysis")
        print("-" * 50)
        analyze_results(results)
        # create_result_comparison_plot(results)

        # Show practical recommendations
        show_practical_recommendations(results)


    except Exception as e:
        print(f"❌ Error in optimization: {e}")
        print(f"   This might be due to network connectivity issues")

    print(f"\n🔄 Running Comparison Analysis...")
    run_comparison_demo()

    print(f"\n🎉 Analysis complete!")


def inspect_network_data(data_file: str):
    """Inspect and summarize the network data"""
    print(f"\n🔍 Network Data Inspection")
    print("-" * 30)

    try:
        with open(data_file, 'r') as f:
            data = json.load(f)

        cities = data.get('cities', list(data.get('city_coordinates', {}).keys()))
        n_cities = len(cities)

        print(f"Cities: {n_cities}")
        print(f"Available cities: {', '.join(cities[:8])}{'...' if n_cities > 8 else ''}")

        # Check data quality
        distance_matrix = np.array(data['distance_matrix'])
        scenic_matrix = np.array(data['scenic_matrix'])

        # Check for infinite distances
        inf_mask = np.isinf(distance_matrix)
        finite_distances = distance_matrix[~inf_mask & (distance_matrix > 0)]

        if len(finite_distances) > 0:
            print(f"Distance range: {np.min(finite_distances) / 1000:.1f} - {np.max(finite_distances) / 1000:.1f} km")
        else:
            print(f"❌ No finite distances found!")

        print(f"Scenic score range: {np.min(scenic_matrix[scenic_matrix > 0]):.1f} - {np.max(scenic_matrix):.1f}")

        # Count available routes (finite distances)
        n_routes = np.sum(~inf_mask & (distance_matrix > 0)) // 2  # Symmetric matrix
        n_infinite = np.sum(inf_mask & (np.arange(n_cities)[:, None] < np.arange(n_cities)))

        print(f"Direct routes: {n_routes}")
        print(f"Infinite distances: {n_infinite}")

        if n_infinite > 0:
            print(f"✅ Network cleaning will handle infinite distances with shortest path routing")

    except Exception as e:
        print(f"❌ Error inspecting data: {e}")


def create_demo_data() -> str:
    """Create synthetic demo data for testing"""
    print("🏗️  Creating synthetic demo network...")

    # Subset of Dutch cities for demo
    cities = ["Leiden", "Amsterdam", "Utrecht", "Rotterdam",
              "The Hague", "Haarlem", "Delft", "Alkmaar"]
    n = len(cities)

    # Set random seed for reproducible results
    np.random.seed(42)

    # Realistic city coordinates (roughly Netherlands)
    coordinates = {
        "Leiden": [52.1601, 4.4970],
        "Amsterdam": [52.3676, 4.9041],
        "Utrecht": [52.0907, 5.1214],
        "Rotterdam": [51.9225, 4.47917],
        "The Hague": [52.0705, 4.3007],
        "Haarlem": [52.3873, 4.6462],
        "Delft": [52.0116, 4.3571],
        "Alkmaar": [52.6318, 4.7516]
    }

    # Generate realistic distance matrix (based on rough coordinates)
    distance_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(i + 1, n):
            lat1, lon1 = coordinates[cities[i]]
            lat2, lon2 = coordinates[cities[j]]

            # Rough distance calculation (not exact, but realistic scale)
            distance = ((lat2 - lat1) ** 2 + (lon2 - lon1) ** 2) ** 0.5 * 111000  # ~111km per degree
            distance *= np.random.uniform(1.2, 1.8)  # Account for roads not being straight

            distance_matrix[i, j] = distance_matrix[j, i] = distance

    # Generate comfort matrices with realistic Dutch characteristics
    scenic_matrix = np.random.uniform(2.5, 4.5, (n, n))  # Moderate to good scenery
    scenic_matrix = (scenic_matrix + scenic_matrix.T) / 2  # Make symmetric

    # Boost scenic scores for specific routes (coastal, historic areas)
    amsterdam_idx = cities.index("Amsterdam")
    haarlem_idx = cities.index("Haarlem")
    scenic_matrix[amsterdam_idx, haarlem_idx] = scenic_matrix[haarlem_idx, amsterdam_idx] = 4.2

    safety_matrix = np.random.uniform(1.5, 3.0, (n, n))  # Generally safe Dutch infrastructure
    safety_matrix = (safety_matrix + safety_matrix.T) / 2

    slope_matrix = np.random.uniform(1.0, 2.2, (n, n))  # Netherlands is flat
    slope_matrix = (slope_matrix + slope_matrix.T) / 2

    roughness_matrix = np.random.uniform(3.8, 4.9, (n, n))  # Excellent Dutch bike paths
    roughness_matrix = (roughness_matrix + roughness_matrix.T) / 2

    # Set diagonal to 0
    np.fill_diagonal(distance_matrix, 0)
    np.fill_diagonal(scenic_matrix, 0)
    np.fill_diagonal(safety_matrix, 0)
    np.fill_diagonal(slope_matrix, 0)
    np.fill_diagonal(roughness_matrix, 0)

    # Create data structure
    demo_data = {
        'cities': cities,
        'city_coordinates': coordinates,
        'distance_matrix': distance_matrix.tolist(),
        'scenic_matrix': scenic_matrix.tolist(),
        'safety_matrix': safety_matrix.tolist(),
        'slope_matrix': slope_matrix.tolist(),
        'roughness_matrix': roughness_matrix.tolist(),
        'metadata': {
            'type': 'synthetic_demo',
            'description': 'Synthetic Dutch bicycle network for demonstration'
        }
    }

    # Save demo data
    demo_file = "demo_dutch_bike_network.json"
    with open(demo_file, 'w') as f:
        json.dump(demo_data, f, indent=2)

    print(f"✅ Created demo data: {demo_file}")
    return demo_file


def show_practical_recommendations(results):
    """Show practical route recommendations"""
    prob = results['problem']
    all_pop = results['population']

    print(f"\n💡 Practical Recommendations")
    print("-" * 45)

    # Get unique valid solutions
    all_solutions = all_pop.get_x()
    all_fitness = all_pop.get_f()

    valid_data = []
    unique_routes = {}

    for sol, fit in zip(all_solutions, all_fitness):
        permutation = prob.decode_permutation(sol)
        _, _, _, is_valid = prob.calculate_route_metrics(permutation)

        if is_valid and fit[0] < 1e5:
            route_sig = tuple(permutation)
            if route_sig not in unique_routes or fit[0] < unique_routes[route_sig][1][0]:
                unique_routes[route_sig] = (sol, fit)

    if len(unique_routes) == 0:
        print("❌ No valid unique routes found")
        return

    valid_solutions = [sol for sol, fit in unique_routes.values()]
    valid_fitness = np.array([fit for sol, fit in unique_routes.values()])

    # Find different types of optimal routes
    min_distance_idx = np.argmin(valid_fitness[:, 0])
    max_comfort_idx = np.argmin(valid_fitness[:, 1])

    # Find balanced solution (closest to ideal point)
    normalized_distance = valid_fitness[:, 0] / np.max(valid_fitness[:, 0])
    normalized_comfort = (-valid_fitness[:, 1]) / np.max(-valid_fitness[:, 1])

    distances_to_ideal = np.sqrt(normalized_distance ** 2 + (1 - normalized_comfort) ** 2)
    balanced_idx = np.argmin(distances_to_ideal)

    recommendations = [
        ("🚴‍♂️ Speed Cyclist", "Shortest distance", min_distance_idx),
        ("🌅 Leisure Cyclist", "Maximum comfort", max_comfort_idx),
        ("⚖️ Balanced Cyclist", "Best compromise", balanced_idx)
    ]

    for cyclist_type, description, idx in recommendations:
        if idx < len(valid_solutions):
            solution = valid_solutions[idx]
            fitness = valid_fitness[idx]

            print(f"\n{cyclist_type} ({description}):")
            print(f"  Distance: {fitness[0]:.1f} km")
            print(f"  Comfort: {-fitness[1]:.2f}/5.0")

            # Get route details
            permutation = prob.decode_permutation(solution)
            cities = [prob.cities[i] for i in permutation]
            route_str = " → ".join(cities)
            print(f"  Route: {route_str}")

            # Calculate additional metrics
            total_distance, avg_comfort, min_comfort, is_valid = prob.calculate_route_metrics(permutation)

            if not is_valid:
                print(f"  ❌ Invalid route (unreachable cities)")
                continue

            print(f"  Minimum segment comfort: {min_comfort:.2f}")
            print(f"  Estimated cycling time: {total_distance / 1000 / 20:.1f} hours at 20km/h")


def run_comparison_demo():
    """Run the comparison demo"""
    print("🚴‍♂️ Dutch Bicycle Route Optimization: Constrained vs Unconstrained")
    print("=" * 70)

    data_file = "real_dutch_bike_network_pygmo.json"

    if not os.path.exists(data_file):
        print(f"⚠️  Real network data '{data_file}' not found.")
        print("📝 First run: python create_dataset.py")
        return

    # 需要导入新函数
    from problem import compare_constrained_vs_unconstrained

    # Run comparison
    results_unc, results_con = compare_constrained_vs_unconstrained(
        data_file=data_file,
        start_city="Leiden",
        target_cities=["Amsterdam", "Utrecht", "Eindhoven"],
        algorithm="nsga2",
        population_size=128,
        generations=20,
        max_route_length=10
    )

    print("\n✅ Comparison completed!")
    return results_unc, results_con


if __name__ == "__main__":
    # Install required packages if not available
    try:
        import pygmo
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError as e:
        print(f"❌ Missing required package: {e}")
        print("📦 Install with: pip install pygmo matplotlib numpy")
        sys.exit(1)

    main()