import numpy as np
import json
import pygmo as pg
from typing import List, Tuple, Dict, Any
import matplotlib.pyplot as plt
from itertools import permutations
import random


class BicycleRoutingProblem:
    """
    Multi-objective bicycle routing optimization problem for pygmo

    Objectives:
    1. Minimize total distance
    2. Maximize comfort (aggregated from selected comfort dimensions)

    Constraints:
    - Selected comfort dimensions must meet minimum thresholds

    Decision variables: Permutation of nodes (cities) to visit
    """

    def __init__(self, data_file: str, start_city: str = "Leiden",
                 target_nodes: List[str] = None,
                 comfort_constraints: Dict[str, float] = None,
                 comfort_objectives: List[str] = None,
                 max_route_length: int = 8,
                 use_penalty_method: bool = True):
        """
        Initialize the bicycle routing problem

        Args:
            data_file: Path to JSON file with network data
            start_city: Starting city (fixed first node)
            target_nodes: Specific nodes that must be visited
            comfort_constraints: Dict of comfort dimensions as constraints with min thresholds
            comfort_objectives: List of comfort dimensions to optimize as objectives
            max_route_length: Maximum number of cities in route (7-10 recommended)
        """
        self.load_network_data(data_file)
        self.start_city = start_city
        self.target_nodes = target_nodes or []
        self.max_route_length = max(7, min(10, max_route_length))  # Clamp to 7-10 range

        # Comfort configuration
        self.comfort_constraints = comfort_constraints or {
            'safety': 2.0,  # Safety must be >= 2.0
            'slope': 2.0  # Slope difficulty must be >= 2.0 (after inversion)
        }
        self.comfort_objectives = comfort_objectives or ['scenic', 'roughness']

        # Prepare city mappings
        self.cities = list(self.city_coordinates.keys())
        self.n_cities = len(self.cities)
        self.city_to_idx = {city: i for i, city in enumerate(self.cities)}
        self.start_idx = self.city_to_idx[start_city]

        # Convert target nodes to indices
        self.target_indices = [self.city_to_idx[city] for city in self.target_nodes]

        self.use_penalty_method = use_penalty_method
        # Penalty weights for constraint violations (if using penalty method)
        self.penalty_weight = 1000.0

        print(f"Problem initialized:")
        print(f"- Cities: {self.n_cities}")
        print(f"- Start: {start_city}")
        print(f"- Target nodes: {self.target_nodes}")
        print(f"- Max route length: {self.max_route_length} cities")
        print(f"- Comfort constraints: {self.comfort_constraints}")
        print(f"- Comfort objectives: {self.comfort_objectives}")

        # Show connectivity information
        self.print_connectivity_info()

    def load_network_data(self, data_file: str):
        """Load network data from JSON file generated by create_dataset.py"""
        with open(data_file, 'r') as f:
            data = json.load(f)

        self.city_coordinates = data['city_coordinates']
        self.distance_matrix = np.array(data['distance_matrix'])
        self.scenic_matrix = np.array(data['scenic_matrix'])
        self.safety_matrix = np.array(data['safety_matrix'])
        self.slope_matrix = np.array(data['slope_matrix'])
        self.roughness_matrix = np.array(data['roughness_matrix'])

        # Clean and analyze network connectivity
        self._clean_network_data()

        print(f"Loaded network with {len(self.city_coordinates)} cities")
        print(f"Direct connections: {self.n_direct_connections}")
        print(f"Connected components: {len(self.connected_components)}")

    def _clean_network_data(self):
        """Clean network data and analyze connectivity"""
        # Replace inf with very large number for algorithms that can't handle inf
        self.inf_mask = np.isinf(self.distance_matrix)
        self.distance_matrix_clean = self.distance_matrix.copy()
        self.distance_matrix_clean[self.inf_mask] = 1e9  # Large but finite number

        # Count direct connections (non-infinite)
        self.n_direct_connections = np.sum(~self.inf_mask & (self.distance_matrix > 0)) // 2

        # Find connected components using Floyd-Warshall for reachability
        n = len(self.city_coordinates)
        reachable = ~self.inf_mask.copy()

        # Floyd-Warshall to find all reachable pairs
        for k in range(n):
            for i in range(n):
                for j in range(n):
                    if reachable[i, k] and reachable[k, j]:
                        reachable[i, j] = True

        # Find connected components
        self.connected_components = []
        visited = set()

        for i in range(n):
            if i not in visited:
                component = set()
                for j in range(n):
                    if reachable[i, j]:
                        component.add(j)
                        visited.add(j)
                self.connected_components.append(component)

        # Store reachability matrix
        self.reachable_matrix = reachable

        # Print connectivity summary
        largest_component = max(self.connected_components, key=len)
        print(f"Largest connected component: {len(largest_component)} cities")

        if len(self.connected_components) > 1:
            print(f"⚠️  Network has disconnected components!")
            for i, component in enumerate(self.connected_components):
                component_cities = [list(self.city_coordinates.keys())[j] for j in component]
                print(f"  Component {i + 1}: {component_cities}")

    def get_reachable_cities(self, start_city: str) -> List[str]:
        """Get list of cities reachable from start city"""
        start_idx = self.city_to_idx[start_city]
        reachable_indices = [i for i in range(self.n_cities)
                             if self.reachable_matrix[start_idx, i]]
        return [self.cities[i] for i in reachable_indices]

    def print_connectivity_info(self):
        """Print detailed connectivity information"""
        print(f"\n🔗 Network Connectivity Analysis")
        print(f"{'=' * 50}")
        print(f"Total cities: {self.n_cities}")
        print(f"Direct connections: {self.n_direct_connections}")
        print(f"Connected components: {len(self.connected_components)}")

        # Show reachable cities from start
        reachable_cities = self.get_reachable_cities(self.start_city)
        print(f"\nFrom {self.start_city}, reachable cities ({len(reachable_cities)}):")
        print(f"  {', '.join(reachable_cities)}")

        # Show unreachable cities
        all_cities = set(self.cities)
        unreachable_cities = all_cities - set(reachable_cities)
        if unreachable_cities:
            print(f"\n❌ Unreachable cities from {self.start_city}:")
            print(f"  {', '.join(unreachable_cities)}")
            print(f"  (These will be excluded from optimization)")

        # Show examples of infinite distances cleaned
        inf_count = np.sum(self.inf_mask & (np.arange(self.n_cities)[:, None] < np.arange(self.n_cities)))
        print(f"\n🧹 Data cleaning:")
        print(f"  Infinite distances found: {inf_count}")
        print(f"  Replaced with large finite values for optimization")
        print(f"  Routes use shortest path algorithm for multi-hop connections")

    def get_bounds(self) -> Tuple[List[float], List[float]]:
        """
        Define bounds for pygmo (permutation encoding)
        For n cities, we use integers 0 to n-1 to represent permutation
        """
        # We'll use a different approach - encode as continuous variables
        # that get converted to permutations
        n_vars = self.n_cities - 1  # Exclude start city
        return ([0.0] * n_vars, [1.0] * n_vars)

    def get_nobj(self) -> int:
        """Number of objectives: 2 (distance, comfort)"""
        return 2

    def get_nec(self) -> int:
        """Number of equality constraints"""
        return 0

    def get_nic(self) -> int:
        """Number of inequality constraints (only if not using penalty method)"""
        if self.use_penalty_method:
            return 0  # No explicit constraints when using penalty method
        else:
            return len(self.comfort_constraints)

    def decode_permutation(self, x: List[float]) -> List[int]:
        """
        Convert continuous variables to permutation that visits all target cities
        Route must end at a target city after visiting all targets with length 7-10
        """
        # Create permutation excluding start city
        available_cities = [i for i in range(self.n_cities) if i != self.start_idx]

        # Sort by x values to create permutation
        sorted_pairs = sorted(zip(x, available_cities), key=lambda pair: pair[0])
        full_permutation = [self.start_idx] + [pair[1] for pair in sorted_pairs]

        # Filter to only include reachable cities
        full_permutation = self.filter_valid_permutation(full_permutation)

        # Build route visiting cities until proper termination
        route = [self.start_idx]
        visited_targets = set()
        remaining_cities = [city for city in full_permutation[1:] if city != self.start_idx]

        # Mix targets and other cities for exploration
        all_cities = remaining_cities.copy()

        for city in all_cities:
            if len(route) >= self.max_route_length:
                break

            route.append(city)

            if city in self.target_indices:
                visited_targets.add(city)

                # Check if we can terminate: all targets visited, length 7-10, ends at target
                if (len(visited_targets) == len(self.target_indices) and
                        len(route) >= 7 and
                        city in self.target_indices):
                    break

        return route

    def calculate_shortest_path(self, start_idx: int, end_idx: int) -> Tuple[float, List[int], float]:
        """
        Calculate shortest path between two cities using Dijkstra's algorithm
        Returns: (distance, path_indices, avg_comfort)
        """
        if self.reachable_matrix[start_idx, end_idx] == False:
            return float('inf'), [], 0.0

        # If direct connection exists, use it
        if not self.inf_mask[start_idx, end_idx]:
            comfort = self._calculate_segment_comfort(start_idx, end_idx)
            return self.distance_matrix[start_idx, end_idx], [start_idx, end_idx], comfort

        # Use Dijkstra's algorithm for multi-hop routing
        n = len(self.cities)
        distances = np.full(n, float('inf'))
        previous = np.full(n, -1)
        comfort_scores = np.zeros(n)
        visited = np.zeros(n, dtype=bool)

        distances[start_idx] = 0.0

        for _ in range(n):
            # Find unvisited node with minimum distance
            current = -1
            min_dist = float('inf')
            for i in range(n):
                if not visited[i] and distances[i] < min_dist:
                    min_dist = distances[i]
                    current = i

            if current == -1 or current == end_idx:
                break

            visited[current] = True

            # Update distances to neighbors
            for neighbor in range(n):
                if not self.inf_mask[current, neighbor] and not visited[neighbor]:
                    new_distance = distances[current] + self.distance_matrix[current, neighbor]

                    if new_distance < distances[neighbor]:
                        distances[neighbor] = new_distance
                        previous[neighbor] = current
                        # Update comfort for this path segment
                        comfort_scores[neighbor] = self._calculate_segment_comfort(current, neighbor)

        # Reconstruct path
        if distances[end_idx] == float('inf'):
            return float('inf'), [], 0.0

        path = []
        current = end_idx
        total_comfort = 0.0
        path_length = 0

        while current != -1:
            path.append(current)
            if current != end_idx:  # Don't count comfort for the destination
                total_comfort += comfort_scores[current]
                path_length += 1
            current = previous[current]

        path.reverse()
        avg_comfort = total_comfort / max(1, path_length)

        return distances[end_idx], path, avg_comfort

    def _calculate_detailed_comfort(self, permutation: List[int]) -> Dict[str, float]:
        """Calculate average score for each comfort dimension"""
        comfort_scores = {'scenic': [], 'safety': [], 'slope': [], 'roughness': []}

        for i in range(len(permutation) - 1):
            city1, city2 = permutation[i], permutation[i + 1]
            if not self.inf_mask[city1, city2]:
                comfort_scores['scenic'].append(self.scenic_matrix[city1, city2])
                comfort_scores['safety'].append(6.0 - self.safety_matrix[city1, city2])  # Inverted
                comfort_scores['slope'].append(6.0 - self.slope_matrix[city1, city2])  # Inverted
                comfort_scores['roughness'].append(self.roughness_matrix[city1, city2])

        # Calculate average for each dimension
        return {dim: np.mean(scores) if scores else 0.0
                for dim, scores in comfort_scores.items()}

    def _calculate_constraint_violations(self, comfort_metrics: Dict[str, float]) -> List[float]:
        """Calculate constraint violation degree (positive = violation)"""
        violations = []

        for constraint_dim, min_threshold in self.comfort_constraints.items():
            if constraint_dim in comfort_metrics:
                actual_value = comfort_metrics[constraint_dim]
                violation = max(0, min_threshold - actual_value)  # Violation degree
                violations.append(violation)
            else:
                violations.append(min_threshold)  # Missing dimension = max violation

        return violations

    def _calculate_objective_comfort(self, comfort_metrics: Dict[str, float]) -> float:
        """Calculate objective comfort score (only from non-constraint dimensions)"""
        objective_scores = [comfort_metrics[dim] for dim in self.comfort_objectives
                            if dim in comfort_metrics]
        return np.mean(objective_scores) if objective_scores else 0.0

    def calculate_route_metrics(self, permutation: List[int]) -> Tuple[float, float, float, bool]:
        """
        Calculate route metrics with strict validation rules

        Returns:
            total_distance: Total route distance
            avg_comfort: Average comfort score (all dimensions)
            min_comfort: Minimum comfort score along route
            is_valid: Route valid if: length 7-10, all targets visited, ends at target
        """
        # Strict validation checks
        route_length = len(permutation)
        visited_targets = set(city for city in permutation if city in self.target_indices)
        all_targets_visited = len(visited_targets) == len(self.target_indices)
        valid_length = 7 <= route_length <= self.max_route_length
        ends_at_target = permutation[-1] in self.target_indices if permutation else False

        is_valid = all_targets_visited and valid_length and ends_at_target

        if not is_valid:
            return float('inf'), 0.0, 0.0, False

        total_distance = 0.0
        comfort_scores = []

        for i in range(len(permutation) - 1):
            city1, city2 = permutation[i], permutation[i + 1]

            # Calculate shortest path between cities
            segment_distance, path, segment_comfort = self.calculate_shortest_path(city1, city2)

            if segment_distance == float('inf'):
                return float('inf'), 0.0, 0.0, False

            total_distance += segment_distance
            if segment_comfort > 0:
                comfort_scores.append(segment_comfort)

        avg_comfort = np.mean(comfort_scores) if comfort_scores else 0.0
        min_comfort = np.min(comfort_scores) if comfort_scores else 0.0

        return total_distance, avg_comfort, min_comfort, True

    def filter_valid_permutation(self, permutation: List[int]) -> List[int]:
        """
        Filter permutation to only include cities reachable from start city
        """
        start_component = None
        for component in self.connected_components:
            if self.start_idx in component:
                start_component = component
                break

        if start_component is None:
            return [self.start_idx]  # Only start city reachable

        # Keep only cities in the same connected component as start
        valid_cities = [city for city in permutation if city in start_component]

        # Ensure start city is first
        if self.start_idx in valid_cities:
            valid_cities.remove(self.start_idx)
        valid_cities.insert(0, self.start_idx)

        return valid_cities

    def _calculate_segment_comfort(self, city1: int, city2: int) -> float:
        """Calculate comfort score for a direct segment between two cities"""
        if self.inf_mask[city1, city2]:
            return 0.0

        scenic = self.scenic_matrix[city1, city2]
        safety = self.safety_matrix[city1, city2]
        slope = self.slope_matrix[city1, city2]
        roughness = self.roughness_matrix[city1, city2]

        # Invert safety and slope scores (lower values = better comfort)
        comfort_safety = 6.0 - safety
        comfort_slope = 6.0 - slope

        comfort = (scenic + comfort_safety + comfort_slope + roughness) / 4.0
        return comfort

    def fitness(self, x: List[float]) -> List[float]:
        # Decode permutation
        permutation = self.decode_permutation(x)

        # Calculate basic metrics
        total_distance, _, _, is_valid = self.calculate_route_metrics(permutation)

        if not is_valid or total_distance == float('inf'):
            # Heavily penalize invalid routes
            obj1 = 1e6  # Distance penalty
            obj2 = -0.0  # Worst comfort

            if self.use_penalty_method:
                return [obj1, obj2]
            else:
                constraints = [1e6] * len(self.comfort_constraints)  # Max constraint violations
                return [obj1, obj2] + constraints

        # Calculate detailed comfort metrics
        comfort_metrics = self._calculate_detailed_comfort(permutation)

        # Base objective functions
        obj1 = total_distance / 1000.0  # Distance in km
        obj2 = -self._calculate_objective_comfort(comfort_metrics)  # Negative for maximization

        if self.use_penalty_method:
            # Apply penalty method: add constraint violations to objectives
            constraint_violations = self._calculate_constraint_violations(comfort_metrics)
            total_violation = sum(constraint_violations)

            if total_violation > 0:
                # Add penalty to both objectives
                obj1 += total_violation * self.penalty_weight
                obj2 += total_violation * 2.0  # Penalty for comfort objective

            return [obj1, obj2]
        else:
            # Return explicit constraints
            constraint_violations = self._calculate_constraint_violations(comfort_metrics)
            return [obj1, obj2] + constraint_violations

    def get_name(self) -> str:
        """Problem name for pygmo"""
        return "Bicycle Route Multi-objective Optimization with Comfort Constraints"

    def pretty_route(self, x: List[float]) -> str:
        """Get human-readable route description with constraint info"""
        permutation = self.decode_permutation(x)
        cities = [self.cities[i] for i in permutation]

        total_distance, avg_comfort, min_comfort, is_valid = self.calculate_route_metrics(permutation)

        if not is_valid:
            route_str = " -> ".join(cities)
            return f"{route_str}\n❌ INVALID ROUTE (validation failed)"

        # Get detailed comfort metrics
        comfort_metrics = self._calculate_detailed_comfort(permutation)
        constraint_violations = self._calculate_constraint_violations(comfort_metrics)
        objective_comfort = self._calculate_objective_comfort(comfort_metrics)

        route_str = " -> ".join(cities)
        metrics_str = f"Distance: {total_distance / 1000:.1f}km, Objective Comfort: {objective_comfort:.2f}"

        # Add constraint status
        constraint_str = ""
        for i, (constraint_dim, min_threshold) in enumerate(self.comfort_constraints.items()):
            actual_value = comfort_metrics.get(constraint_dim, 0.0)
            violation = constraint_violations[i]
            status = "✅" if violation == 0 else "❌"
            constraint_str += f"\n{status} {constraint_dim}: {actual_value:.2f} (req: ≥{min_threshold})"

        return f"{route_str}\n{metrics_str}{constraint_str}"


def run_optimization(data_file: str, start_city: str = "Leiden",
                     target_cities: List[str] = None, algorithm: str = "nsga2",
                     population_size: int = 100, generations: int = 50,
                     max_route_length: int = 8,
                     comfort_constraints: Dict[str, float] = None,
                     comfort_objectives: List[str] = None,
                     use_penalty_method: bool = True) -> Dict[str, Any]:
    """
    Run multi-objective optimization for bicycle routing with comfort constraints

    Args:
        data_file: Path to network data JSON file
        start_city: Starting city
        target_cities: Cities that must be visited
        algorithm: Optimization algorithm ("nsga2", "moead", "sms_emoa", "gaco")
        population_size: Size of population
        generations: Number of generations
        max_route_length: Maximum route length
        comfort_constraints: Dict of comfort dimensions as constraints
        comfort_objectives: List of comfort dimensions as objectives
        use_penalty_method: If True, use penalty method instead of explicit constraints

    Returns:
        Dictionary with results including Pareto front
    """
    print(f"Running bicycle route optimization with constraints...")
    print(f"Algorithm: {algorithm}, Population: {population_size}, Generations: {generations}")
    print(f"Constraint handling: {'Penalty method' if use_penalty_method else 'Explicit constraints'}")

    # Create problem with constraints
    prob = BicycleRoutingProblem(
        data_file=data_file,
        start_city=start_city,
        target_nodes=target_cities or [],
        comfort_constraints=comfort_constraints or {'safety': 2.0, 'slope': 2.0},
        comfort_objectives=comfort_objectives or ['scenic', 'roughness'],
        max_route_length=max_route_length,
        use_penalty_method=use_penalty_method
    )

    # Wrap for pygmo
    udp = pg.problem(prob)

    # Select algorithm based on constraint handling capability
    if use_penalty_method or prob.get_nic() == 0:
        # Use unconstrained algorithms with penalty method
        if algorithm == "nsga2":
            algo = pg.algorithm(pg.nsga2(gen=generations))
        elif algorithm == "moead":
            algo = pg.algorithm(pg.moead(gen=generations))
        elif algorithm == "sms_emoa":
            algo = pg.algorithm(pg.sms_emoa(gen=generations))
        else:
            print(f"⚠️  Unknown algorithm '{algorithm}', using NSGA-II as default")
            algo = pg.algorithm(pg.nsga2(gen=generations))
    else:
        # Use constrained algorithms for explicit constraints
        if algorithm == "gaco":
            # Genetic Algorithm with Constraint Handling
            algo = pg.algorithm(pg.gaco(gen=generations, ker=63))
        elif algorithm == "ihs":
            # Improved Harmony Search
            algo = pg.algorithm(pg.ihs(gen=generations))
        else:
            print(f"⚠️  Algorithm '{algorithm}' doesn't support constraints, using penalty method with NSGA-II")
            prob.use_penalty_method = True
            algo = pg.algorithm(pg.nsga2(gen=generations))

    # Create population
    pop = pg.population(udp, population_size)

    print(f"Initial population fitness range:")
    fits = pop.get_f()
    print(f"Distance: [{np.min(fits[:, 0]):.1f}, {np.max(fits[:, 0]):.1f}] km")
    print(f"Comfort: [{-np.max(fits[:, 1]):.2f}, {-np.min(fits[:, 1]):.2f}]")

    if fits.shape[1] > 2:
        print(f"Constraint violations: {np.sum(fits[:, 2:] > 0, axis=1).tolist()}")

    # Run optimization
    pop = algo.evolve(pop)

    print(f"Final population fitness range:")
    fits = pop.get_f()
    print(f"Distance: [{np.min(fits[:, 0]):.1f}, {np.max(fits[:, 0]):.1f}] km")
    print(f"Comfort: [{-np.max(fits[:, 1]):.2f}, {-np.min(fits[:, 1]):.2f}]")

    if fits.shape[1] > 2:
        feasible_count = np.sum(np.all(fits[:, 2:] <= 0, axis=1))
        print(f"Feasible solutions: {feasible_count}/{len(fits)}")

    # Extract Pareto front
    if use_penalty_method or prob.get_nic() == 0:
        # For penalty method, use standard Pareto front extraction
        pareto_front_idx = pg.non_dominated_front_2d(fits[:, :2])
    else:
        # For explicit constraints, only consider feasible solutions
        feasible_mask = np.all(fits[:, 2:] <= 0, axis=1) if fits.shape[1] > 2 else np.ones(len(fits), dtype=bool)

        if np.any(feasible_mask):
            feasible_fits = fits[feasible_mask]
            pareto_front_idx = pg.non_dominated_front_2d(feasible_fits[:, :2])
            # Map back to original indices
            feasible_indices = np.where(feasible_mask)[0]
            pareto_front_idx = feasible_indices[pareto_front_idx]
        else:
            print("⚠️  No feasible solutions found!")
            pareto_front_idx = []

    pareto_front_f = fits[pareto_front_idx] if len(pareto_front_idx) > 0 else np.array([])
    pareto_front_x = pop.get_x()[pareto_front_idx] if len(pareto_front_idx) > 0 else np.array([])

    print(f"Pareto front contains {len(pareto_front_idx)} solutions")

    return {
        'problem': prob,
        'population': pop,
        'pareto_front_indices': pareto_front_idx,
        'pareto_front_fitness': pareto_front_f,
        'pareto_front_solutions': pareto_front_x,
        'algorithm': algorithm,
        'use_penalty_method': use_penalty_method
    }
    """
    Run multi-objective optimization for bicycle routing with comfort constraints

    Args:
        data_file: Path to network data JSON file
        start_city: Starting city
        target_cities: Cities that must be visited
        algorithm: Optimization algorithm ("nsga2", "moead", "sms_emoa")
        population_size: Size of population
        generations: Number of generations
        max_route_length: Maximum route length
        comfort_constraints: Dict of comfort dimensions as constraints
        comfort_objectives: List of comfort dimensions as objectives

    Returns:
        Dictionary with results including Pareto front
    """
    print(f"Running bicycle route optimization with constraints...")
    print(f"Algorithm: {algorithm}, Population: {population_size}, Generations: {generations}")

    # Create problem with constraints
    prob = BicycleRoutingProblem(
        data_file=data_file,
        start_city=start_city,
        target_nodes=target_cities or [],
        comfort_constraints=comfort_constraints or {'safety': 2.0, 'slope': 2.0},
        comfort_objectives=comfort_objectives or ['scenic', 'roughness'],
        max_route_length=max_route_length
    )

    # Wrap for pygmo
    udp = pg.problem(prob)

    # Select algorithm
    if algorithm == "nsga2":
        algo = pg.algorithm(pg.nsga2(gen=generations))
    elif algorithm == "moead":
        algo = pg.algorithm(pg.moead(gen=generations))
    elif algorithm == "mhaco":
        # Multi-objective Ant Colony Optimization
        algo = pg.algorithm(pg.mhaco(gen=generations))
    elif algorithm == "nspso":
        # Non-dominated Sorting Particle Swarm Optimization
        algo = pg.algorithm(pg.nspso(gen=generations))
    else:
        print(f"⚠️  Unknown algorithm '{algorithm}', using NSGA-II as default")
        algo = pg.algorithm(pg.nsga2(gen=generations))

    # Create population
    pop = pg.population(udp, population_size)

    print(f"Initial population fitness range:")
    fits = pop.get_f()
    print(f"Distance: [{np.min(fits[:, 0]):.1f}, {np.max(fits[:, 0]):.1f}] km")
    print(f"Comfort: [{-np.max(fits[:, 1]):.2f}, {-np.min(fits[:, 1]):.2f}]")

    if fits.shape[1] > 2:
        print(f"Constraint violations: {np.sum(fits[:, 2:] > 0, axis=1).tolist()}")

    # Run optimization
    pop = algo.evolve(pop)

    print(f"Final population fitness range:")
    fits = pop.get_f()
    print(f"Distance: [{np.min(fits[:, 0]):.1f}, {np.max(fits[:, 0]):.1f}] km")
    print(f"Comfort: [{-np.max(fits[:, 1]):.2f}, {-np.min(fits[:, 1]):.2f}]")

    if fits.shape[1] > 2:
        print(f"Constraint violations: {np.sum(fits[:, 2:] > 0, axis=1).tolist()}")

    # Extract Pareto front (only from feasible solutions)
    feasible_mask = np.all(fits[:, 2:] <= 0, axis=1) if fits.shape[1] > 2 else np.ones(len(fits), dtype=bool)

    if np.any(feasible_mask):
        feasible_fits = fits[feasible_mask]
        pareto_front_idx = pg.non_dominated_front_2d(feasible_fits[:, :2])
        # Map back to original indices
        feasible_indices = np.where(feasible_mask)[0]
        pareto_front_idx = feasible_indices[pareto_front_idx]
    else:
        print("⚠️  No feasible solutions found!")
        pareto_front_idx = []

    pareto_front_f = fits[pareto_front_idx] if len(pareto_front_idx) > 0 else np.array([])
    pareto_front_x = pop.get_x()[pareto_front_idx] if len(pareto_front_idx) > 0 else np.array([])

    print(f"Feasible solutions: {np.sum(feasible_mask)}/{len(fits)}")
    print(f"Pareto front contains {len(pareto_front_idx)} solutions")

    return {
        'problem': prob,
        'population': pop,
        'pareto_front_indices': pareto_front_idx,
        'pareto_front_fitness': pareto_front_f,
        'pareto_front_solutions': pareto_front_x,
        'algorithm': algorithm,
        'feasible_mask': feasible_mask
    }


def analyze_results(results: Dict[str, Any]) -> None:
    """Enhanced visualization similar to the reference paper"""
    prob = results['problem']
    pareto_f = results['pareto_front_fitness']
    pareto_x = results['pareto_front_solutions']
    all_pop = results['population']

    # Extract all solutions
    all_solutions = all_pop.get_x()
    all_fitness = all_pop.get_f()

    # Convert fitness for plotting (distance in km, comfort as positive)
    all_distances = all_fitness[:, 0]
    all_comfort = -all_fitness[:, 1]  # Convert back to positive

    if len(pareto_f) > 0:
        pareto_distances = pareto_f[:, 0]
        pareto_comfort = -pareto_f[:, 1]

    # Create cleaner visualization
    plt.figure(figsize=(16, 6))

    # Plot 1: Clean Pareto front visualization (like reference paper)
    plt.subplot(1, 2, 1)

    # Plot all solutions as light gray points
    plt.scatter(all_distances, all_comfort,
                c='lightgray', alpha=0.6, s=25,
                label=f'All solutions ({len(all_fitness)})')

    # Highlight Pareto front with distinctive red line and markers
    if len(pareto_f) > 0:
        # Sort Pareto points by distance for clean line connection
        sorted_indices = np.argsort(pareto_distances)
        sorted_distances = pareto_distances[sorted_indices]
        sorted_comfort = pareto_comfort[sorted_indices]

        # Plot Pareto front as connected line (like reference)
        plt.plot(sorted_distances, sorted_comfort,
                 'r-', linewidth=3, alpha=0.8, label='Pareto Front')
        plt.scatter(sorted_distances, sorted_comfort,
                    c='red', s=80, marker='o',
                    edgecolors='darkred', linewidths=2, zorder=5)

    plt.xlabel('Distance (km)', fontsize=12, fontweight='bold')
    plt.ylabel('Average Comfort Score', fontsize=12, fontweight='bold')
    plt.title('Pareto Front for Bicycle Route Optimization', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=11)

    # Plot 2: Constraint satisfaction with better visualization
    plt.subplot(1, 2, 2)

    if len(all_fitness) > 0 and all_fitness.shape[1] > 2:
        # Show constraint satisfaction clearly
        constraint_violations = all_fitness[:, 2:]
        feasible_mask = np.all(constraint_violations <= 0, axis=1)

        # Feasible solutions in green
        if np.any(feasible_mask):
            plt.scatter(all_distances[feasible_mask], all_comfort[feasible_mask],
                        c='green', alpha=0.7, s=50, marker='o',
                        label=f'Feasible solutions ({np.sum(feasible_mask)})')

        # Infeasible solutions in red
        if np.any(~feasible_mask):
            plt.scatter(all_distances[~feasible_mask], all_comfort[~feasible_mask],
                        c='red', alpha=0.7, s=50, marker='x',
                        label=f'Infeasible solutions ({np.sum(~feasible_mask)})')

        # Highlight Pareto front feasible solutions
        if len(pareto_f) > 0:
            pareto_feasible = np.all(pareto_f[:, 2:] <= 0, axis=1) if pareto_f.shape[1] > 2 else np.ones(len(pareto_f),
                                                                                                         dtype=bool)
            if np.any(pareto_feasible):
                feasible_pareto_dist = pareto_distances[pareto_feasible]
                feasible_pareto_comfort = pareto_comfort[pareto_feasible]
                plt.scatter(feasible_pareto_dist, feasible_pareto_comfort,
                            c='blue', s=100, marker='*',
                            edgecolors='navy', linewidths=2,
                            label=f'Pareto optimal ({np.sum(pareto_feasible)})', zorder=5)
    else:
        # No constraints case
        plt.scatter(all_distances, all_comfort, c='green', alpha=0.7, s=50,
                    label='All solutions (unconstrained)')
        if len(pareto_f) > 0:
            plt.scatter(pareto_distances, pareto_comfort, c='red', s=100, marker='*',
                        label='Pareto front', zorder=5)

    plt.xlabel('Distance (km)', fontsize=12, fontweight='bold')
    plt.ylabel('Average Comfort Score', fontsize=12, fontweight='bold')
    plt.title('Solution Feasibility Analysis', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=11)

    plt.tight_layout()
    plt.show()

    # Print clear statistics (like reference paper)
    print(f"\n{'=' * 60}")
    print(f"OPTIMIZATION RESULTS SUMMARY")
    print(f"{'=' * 60}")

    if len(pareto_f) > 0:
        print(f"📊 Pareto Front Statistics:")
        print(f"   • Number of Pareto-optimal solutions: {len(pareto_f)}")
        print(f"   • Distance range: {np.min(pareto_distances):.1f} - {np.max(pareto_distances):.1f} km")
        print(f"   • Comfort range: {np.min(pareto_comfort):.2f} - {np.max(pareto_comfort):.2f}")

        # Show constraint satisfaction
        if pareto_f.shape[1] > 2:
            pareto_feasible_count = np.sum(np.all(pareto_f[:, 2:] <= 0, axis=1))
            print(f"   • Feasible Pareto solutions: {pareto_feasible_count}/{len(pareto_f)}")

    print(f"\n🎯 Algorithm Performance:")
    print(f"   • Total solutions evaluated: {len(all_fitness)}")
    if all_fitness.shape[1] > 2:
        feasible_count = np.sum(np.all(all_fitness[:, 2:] <= 0, axis=1))
        print(
            f"   • Feasible solutions: {feasible_count}/{len(all_fitness)} ({100 * feasible_count / len(all_fitness):.1f}%)")

    print(
        f"   • Constraint handling: {'Penalty Method' if results.get('use_penalty_method', True) else 'Explicit Constraints'}")
    print(f"   • Algorithm: {results.get('algorithm', 'Unknown')}")


def create_result_comparison_plot(results: Dict[str, Any]):
    """Create a comparison plot similar to the reference paper"""
    prob = results['problem']
    pareto_f = results['pareto_front_fitness']
    all_fitness = results['population'].get_f()

    if len(pareto_f) == 0:
        print("No Pareto solutions to plot")
        return

    plt.figure(figsize=(12, 8))

    # Convert to plot-friendly format
    all_distances = all_fitness[:, 0]
    all_comfort = -all_fitness[:, 1]
    pareto_distances = pareto_f[:, 0]
    pareto_comfort = -pareto_f[:, 1]

    # Main plot similar to reference paper style
    plt.scatter(all_distances, all_comfort,
                c='lightgray', alpha=0.6, s=30, label='All solutions')

    # Sort and connect Pareto front
    sorted_indices = np.argsort(pareto_distances)
    sorted_distances = pareto_distances[sorted_indices]
    sorted_comfort = pareto_comfort[sorted_indices]

    plt.plot(sorted_distances, sorted_comfort,
             'r-', linewidth=4, alpha=0.9, label='Pareto Front')
    plt.scatter(sorted_distances, sorted_comfort,
                c='red', s=100, marker='o',
                edgecolors='darkred', linewidths=2, zorder=5)

    plt.xlabel('Distance (km)', fontsize=14, fontweight='bold')
    plt.ylabel('Average Comfort Score', fontsize=14, fontweight='bold')
    plt.title('Pareto Front for Multi-Objective Bicycle Route Optimization\nwith Comfort Constraints',
              fontsize=16, fontweight='bold', pad=20)
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=12, loc='upper right')

    # Add text box with key statistics
    textstr = f'Solutions: {len(pareto_f)} Pareto-optimal\n'
    textstr += f'Distance: {np.min(pareto_distances):.0f}-{np.max(pareto_distances):.0f} km\n'
    textstr += f'Comfort: {np.min(pareto_comfort):.2f}-{np.max(pareto_comfort):.2f}'

    props = dict(boxstyle='round', facecolor='white', alpha=0.8)
    plt.text(0.02, 0.98, textstr, transform=plt.gca().transAxes, fontsize=11,
             verticalalignment='top', bbox=props)

    plt.tight_layout()
    plt.show()



def demo_constrained_optimization():
    """
    Demonstrate the enhanced algorithm with comfort constraints
    """
    print(f"{'=' * 60}")
    print(f"DEMO: Constrained Bicycle Route Optimization")
    print(f"{'=' * 60}")

    # Example 1: Safety and slope as constraints, scenic and roughness as objectives
    print("\n--- Example 1: Safety + Slope Constraints ---")
    try:
        results1 = run_optimization(
            data_file='real_dutch_bike_network_pygmo.json',
            start_city="Amsterdam",
            target_cities=["Utrecht", "Rotterdam", "Eindhoven"],
            algorithm="nsga2",
            population_size=80,
            generations=30,
            max_route_length=8,
            comfort_constraints={
                'safety': 2.5,  # Safety must be >= 2.5
                'slope': 2.0  # Slope difficulty must be >= 2.0
            },
            comfort_objectives=['scenic', 'roughness']  # Optimize scenic beauty and surface quality
        )

        print("✅ Example 1 completed")
        analyze_results(results1)

    except FileNotFoundError:
        print("Real network data not found. Creating synthetic demo...")
        create_synthetic_constrained_demo()

    # Example 2: Only scenic beauty as constraint, others as objectives
    print("\n--- Example 2: Scenic Beauty Constraint ---")
    try:
        results2 = run_optimization(
            data_file='real_dutch_bike_network_pygmo.json',
            start_city="Leiden",
            target_cities=["Amsterdam", "Utrecht"],
            algorithm="nsga2",
            population_size=60,
            generations=25,
            max_route_length=7,
            comfort_constraints={
                'scenic': 3.0  # Scenic beauty must be >= 3.0
            },
            comfort_objectives=['safety', 'slope', 'roughness']  # Optimize all other dimensions
        )

        print("✅ Example 2 completed")
        analyze_results(results2)

    except FileNotFoundError:
        print("Using synthetic data for Example 2...")


def create_synthetic_constrained_demo():
    """Create synthetic demo with realistic constraint scenarios"""
    print("🏗️  Creating synthetic constrained demo...")

    # Create demo data similar to previous function but with more realistic comfort variation
    cities = ["Amsterdam", "Utrecht", "Rotterdam", "Eindhoven", "Leiden", "Haarlem", "Delft"]
    n = len(cities)

    np.random.seed(42)

    # Generate distance matrix
    distance_matrix = np.random.uniform(25, 90, (n, n))
    distance_matrix = (distance_matrix + distance_matrix.T) / 2
    np.fill_diagonal(distance_matrix, 0)

    # Generate comfort matrices with realistic Dutch characteristics and more variation
    scenic_matrix = np.random.uniform(2.0, 4.8, (n, n))
    scenic_matrix = (scenic_matrix + scenic_matrix.T) / 2
    np.fill_diagonal(scenic_matrix, 0)

    # Safety: Generally good but some variation
    safety_matrix = np.random.uniform(1.2, 3.5, (n, n))
    safety_matrix = (safety_matrix + safety_matrix.T) / 2
    np.fill_diagonal(safety_matrix, 0)

    # Slope: Mostly flat with some hills
    slope_matrix = np.random.uniform(1.0, 2.8, (n, n))
    slope_matrix = (slope_matrix + slope_matrix.T) / 2
    np.fill_diagonal(slope_matrix, 0)

    # Roughness: High quality Dutch infrastructure with some variation
    roughness_matrix = np.random.uniform(3.2, 4.9, (n, n))
    roughness_matrix = (roughness_matrix + roughness_matrix.T) / 2
    np.fill_diagonal(roughness_matrix, 0)

    # Create synthetic data structure
    synthetic_data = {
        'cities': cities,
        'city_coordinates': {city: (52.0 + i * 0.1, 4.5 + i * 0.1) for i, city in enumerate(cities)},
        'distance_matrix': (distance_matrix * 1000).tolist(),  # Convert to meters
        'scenic_matrix': scenic_matrix.tolist(),
        'safety_matrix': safety_matrix.tolist(),
        'slope_matrix': slope_matrix.tolist(),
        'roughness_matrix': roughness_matrix.tolist()
    }

    # Save synthetic data
    with open('synthetic_constrained_bike_network.json', 'w') as f:
        json.dump(synthetic_data, f, indent=2)

    print("✅ Created constrained synthetic network data")

    # Run both constraint examples with synthetic data
    print("\n--- Synthetic Example 1: Multiple Constraints ---")
    results1 = run_optimization(
        data_file='synthetic_constrained_bike_network.json',
        start_city="Amsterdam",
        target_cities=["Utrecht", "Eindhoven"],
        algorithm="nsga2",
        population_size=60,
        generations=20,
        max_route_length=7,
        comfort_constraints={
            'safety': 2.5,
            'slope': 2.0
        },
        comfort_objectives=['scenic', 'roughness']
    )
    analyze_results(results1)

    print("\n--- Synthetic Example 2: Single Constraint ---")
    results2 = run_optimization(
        data_file='synthetic_constrained_bike_network.json',
        start_city="Leiden",
        target_cities=["Amsterdam"],
        algorithm="nsga2",
        population_size=40,
        generations=15,
        max_route_length=7,
        comfort_constraints={
            'scenic': 3.0
        },
        comfort_objectives=['safety', 'slope', 'roughness']
    )
    analyze_results(results2)


def compare_constrained_vs_unconstrained(data_file: str, start_city: str = "Leiden",
                                         target_cities: List[str] = None,
                                         algorithm: str = "nsga2",
                                         population_size: int = 128,
                                         generations: int = 20,
                                         max_route_length: int = 10):
    """
    Compare constrained vs unconstrained optimization results in one overlay plot
    """
    print("🔍 Running Constrained vs Unconstrained Comparison")
    print("=" * 60)

    # Run unconstrained optimization
    print("\n1️⃣ Running UNCONSTRAINED optimization...")
    results_unconstrained = run_optimization(
        data_file=data_file,
        start_city=start_city,
        target_cities=target_cities,
        algorithm=algorithm,
        population_size=population_size,
        generations=generations,
        max_route_length=max_route_length,
        comfort_constraints={},  # 无约束
        comfort_objectives=['scenic', 'roughness', 'safety', 'slope'],  # 所有维度作为目标
        use_penalty_method=True
    )

    # Run constrained optimization
    print("\n2️⃣ Running CONSTRAINED optimization...")
    results_constrained = run_optimization(
        data_file=data_file,
        start_city=start_city,
        target_cities=target_cities,
        algorithm=algorithm,
        population_size=population_size,
        generations=generations,
        max_route_length=max_route_length,
        comfort_constraints={'safety': 2.0, 'slope': 2.0},  # 带约束
        comfort_objectives=['scenic', 'roughness'],  # 部分维度作为目标
        use_penalty_method=True
    )

    # Create single overlay comparison plot
    create_single_comparison_plot(results_unconstrained, results_constrained)

    return results_unconstrained, results_constrained


def create_single_comparison_plot(results_unconstrained: Dict[str, Any],
                                  results_constrained: Dict[str, Any]):
    """
    Create single overlay comparison plot with deduplication
    """

    def deduplicate_solutions(results):
        """去重并返回唯一解"""
        prob = results['problem']
        all_solutions = results['population'].get_x()
        all_fitness = results['population'].get_f()
        pareto_f = results['pareto_front_fitness']
        pareto_x = results['pareto_front_solutions']

        # 去重所有解
        unique_solutions = {}
        for sol, fit in zip(all_solutions, all_fitness):
            permutation = prob.decode_permutation(sol)
            _, _, _, is_valid = prob.calculate_route_metrics(permutation)

            if is_valid and fit[0] < 1e5:
                route_sig = tuple(permutation)
                if route_sig not in unique_solutions or fit[0] < unique_solutions[route_sig][1][0]:
                    unique_solutions[route_sig] = (sol, fit)

        # 去重帕累托解
        unique_pareto = {}
        for sol, fit in zip(pareto_x, pareto_f):
            permutation = prob.decode_permutation(sol)
            route_sig = tuple(permutation)
            if route_sig in unique_solutions:  # 只包含有效且唯一的解
                unique_pareto[route_sig] = (sol, fit)

        unique_all_fitness = np.array([fit for sol, fit in unique_solutions.values()])
        unique_pareto_fitness = np.array([fit for sol, fit in unique_pareto.values()])

        return unique_all_fitness, unique_pareto_fitness, len(all_solutions), len(pareto_f)

    # 对两个结果都进行去重
    print("🔄 Deduplicating solutions...")

    unc_fitness, unc_pareto_f, unc_total, unc_pareto_total = deduplicate_solutions(results_unconstrained)
    con_fitness, con_pareto_f, con_total, con_pareto_total = deduplicate_solutions(results_constrained)

    print(
        f"Unconstrained: {len(unc_fitness)}/{unc_total} unique solutions, {len(unc_pareto_f)}/{unc_pareto_total} unique Pareto")
    print(
        f"Constrained: {len(con_fitness)}/{con_total} unique solutions, {len(con_pareto_f)}/{con_pareto_total} unique Pareto")

    # 检查是否有有效数据
    if len(unc_fitness) == 0 or len(con_fitness) == 0:
        print("❌ No valid unique solutions found for comparison")
        return

    # Convert to plot-friendly format (使用去重后的数据)
    unc_distances = unc_fitness[:, 0]
    unc_comfort = -unc_fitness[:, 1]
    unc_pareto_distances = unc_pareto_f[:, 0] if len(unc_pareto_f) > 0 else []
    unc_pareto_comfort = -unc_pareto_f[:, 1] if len(unc_pareto_f) > 0 else []

    con_distances = con_fitness[:, 0]
    con_comfort = -con_fitness[:, 1]
    con_pareto_distances = con_pareto_f[:, 0] if len(con_pareto_f) > 0 else []
    con_pareto_comfort = -con_pareto_f[:, 1] if len(con_pareto_f) > 0 else []

    # Create single overlay plot
    plt.figure(figsize=(12, 8))

    # Plot unconstrained data (background)
    plt.scatter(unc_distances, unc_comfort, c='lightblue', alpha=0.4, s=25,
                label=f'Unconstrained solutions ({len(unc_fitness)})')

    # Plot unconstrained Pareto front
    if len(unc_pareto_distances) > 0:
        sorted_indices = np.argsort(unc_pareto_distances)
        sorted_dist = np.array(unc_pareto_distances)[sorted_indices]
        sorted_comfort = np.array(unc_pareto_comfort)[sorted_indices]
        plt.plot(sorted_dist, sorted_comfort, 'b-', linewidth=2,
                 label=f'Unconstrained Pareto ({len(unc_pareto_f)})', alpha=0.7)
        plt.scatter(unc_pareto_distances, unc_pareto_comfort, c='blue', s=60,
                    marker='o', edgecolors='darkblue', linewidths=1, alpha=0.8)

    # Plot constrained data (foreground)
    plt.scatter(con_distances, con_comfort, c='lightcoral', alpha=0.6, s=35,
                label=f'Constrained solutions ({len(con_fitness)})')

    # Plot constrained Pareto front (most prominent)
    if len(con_pareto_distances) > 0:
        sorted_indices = np.argsort(con_pareto_distances)
        sorted_dist = np.array(con_pareto_distances)[sorted_indices]
        sorted_comfort = np.array(con_pareto_comfort)[sorted_indices]
        plt.plot(sorted_dist, sorted_comfort, 'r-', linewidth=4,
                 label=f'Constrained Pareto ({len(con_pareto_f)})', alpha=0.9)
        plt.scatter(con_pareto_distances, con_pareto_comfort, c='red', s=100,
                    marker='*', edgecolors='darkred', linewidths=2, zorder=5)

    plt.xlabel('Distance (km)', fontsize=14, fontweight='bold')
    plt.ylabel('Average Comfort Score', fontsize=14, fontweight='bold')
    plt.title('Constrained vs Unconstrained Bicycle Route Optimization\n(Safety≥2.0, Slope≥2.0)',
              fontsize=16, fontweight='bold', pad=20)
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=12, loc='upper right')

    # Add summary text box
    textstr = f'Unconstrained: {len(unc_pareto_f)} Pareto solutions\n'
    textstr += f'Constrained: {len(con_pareto_f)} Pareto solutions\n'
    if len(unc_distances) > 0 and len(con_distances) > 0:
        textstr += f'Distance range: {min(np.min(unc_distances), np.min(con_distances)):.0f}-{max(np.max(unc_distances), np.max(con_distances)):.0f} km\n'
        textstr += f'Comfort range: {min(np.min(unc_comfort), np.min(con_comfort)):.2f}-{max(np.max(unc_comfort), np.max(con_comfort)):.2f}'

    props = dict(boxstyle='round', facecolor='white', alpha=0.9)
    plt.text(0.02, 0.98, textstr, transform=plt.gca().transAxes, fontsize=11,
             verticalalignment='top', bbox=props)

    plt.tight_layout()
    plt.show()

    # Print comparison statistics
    print(f"\n📊 COMPARISON STATISTICS (DEDUPLICATED)")
    print("=" * 60)
    print(f"{'Metric':<30} {'Unconstrained':<15} {'Constrained':<15}")
    print("-" * 60)
    print(f"{'Total Solutions (Original)':<30} {unc_total:<15} {con_total:<15}")
    print(f"{'Unique Solutions':<30} {len(unc_fitness):<15} {len(con_fitness):<15}")
    print(f"{'Pareto Solutions (Original)':<30} {unc_pareto_total:<15} {con_pareto_total:<15}")
    print(f"{'Unique Pareto Solutions':<30} {len(unc_pareto_f):<15} {len(con_pareto_f):<15}")
    print(
        f"{'Deduplication Ratio':<30} {len(unc_fitness) / unc_total * 100:.1f}%{'':<10} {len(con_fitness) / con_total * 100:.1f}%")

    if len(unc_distances) > 0 and len(con_distances) > 0:
        print(
            f"{'Distance Range (km)':<30} {np.min(unc_distances):.0f}-{np.max(unc_distances):.0f} {'':>6} {np.min(con_distances):.0f}-{np.max(con_distances):.0f}")
        print(
            f"{'Comfort Range':<30} {np.min(unc_comfort):.2f}-{np.max(unc_comfort):.2f} {'':>8} {np.min(con_comfort):.2f}-{np.max(con_comfort):.2f}")


if __name__ == "__main__":
    # Run the constrained optimization demonstration
    demo_constrained_optimization()