# -*- coding: utf-8 -*-
"""A2_GenerativeModels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuCHg18ij3Ui4T218vsptCSZFDM_TG93

# Introduction to Deep Learning

In this notebook we are going to cover two generative models for generating novel images:

1. Variational Autoencoders (**VAEs**)
2. Generative adversarial networks (**GANs**)


<img src="https://lilianweng.github.io/lil-log/assets/images/three-generative-models.png" width="500">


You should first copy this notebook and enable GPU runtime in 'Runtime -> Change runtime type -> Hardware acceleration -> GPU **OR** TPU'.

In this assignment we use google drive to load our datasets.
"""

import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'

from tqdm import tqdm
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive', force_remount=True) ## We use google drive to upload our own datasets

"""
### Dataset

Faces in the Wild (LFW) is a database of face photos. 1,680 people in the photos
have two or more different photos in the dataset. The original database contains four
different sets of LFW images and three different types of ”aligned” images. We choose
this database as the training set for this experiment

### Dataset Loading

Remember to dynamically adjust the file path according to your file_path."""

def load_real_samples(file_path='/content/drive/MyDrive/Dataset/preprocessed_data.npy', scale=False):
    X = np.load(file_path, allow_pickle=True)  # loading dataset
    X = X.astype('float32')
    if scale:
        # descale to [-1, 1]
        X = (X - 127.5) / 127.5
    else:
        # normalize [0, 1]
        X = X / 255.0

    return X

def grid_plot(images, name='', n=3, save=False):
    for index in range(n * n):
        plt.subplot(n, n, 1 + index)
        plt.axis('off')
        plt.imshow(images[index])
    fig = plt.gcf()
    fig.suptitle(name, fontsize=14)
    plt.show()


# test
file_path = '/content/drive/MyDrive/Dataset/preprocessed_data.npy'
dataset = load_real_samples(file_path)
print(f"Data type: {dataset.dtype}")
print(f"Dataset shape: {dataset.shape}")
print(f"Dataset min: {dataset.min()}, max: {dataset.max()}")

images = dataset[np.random.randint(0, dataset.shape[0], 9)]
grid_plot(images, name='Fliqr dataset (64x64x3)', n=3)

"""## 2.1. Introduction

#### Our Improvements:
For encoder, we increase the original four convolutional layers to six layers;A fixed number of filters is set in the initial layer. As the network depth increases, the number of filters increases layer by layer. The number of filters in the first three layers is 128, 256, and 512, respectively, and remains unchanged from the fourth layer. We also add Batch Normalization to improve training stability.

For decoder, the number of filters is halved from 512 to 64 while areshape layer is added to convert the latent vector into the corresponding feature map.
"""

from tensorflow.keras.layers import Dense, Flatten, Conv2D, Conv2DTranspose, Reshape, BatchNormalization, Dropout, LeakyReLU, Activation

def build_conv_net(in_shape, out_shape, n_downsampling_layers=6, filters=128, out_activation='sigmoid'):
    """
    Build a deeper convolutional encoder network.
    """
    default_args = dict(kernel_size=(3, 3), strides=(2, 2), padding='same', activation='relu')

    input = tf.keras.Input(shape=in_shape)
    x = Conv2D(filters=filters, name='enc_input', **default_args)(input)

    for i in range(n_downsampling_layers):
        x = Conv2D(filters=filters * (2 ** min(i, 3)), **default_args)(x)

    x = Flatten()(x)
    x = Dense(out_shape, activation=out_activation, name='enc_output')(x)

    model = tf.keras.Model(inputs=input, outputs=x, name='Encoder')

    model.summary()
    return model



def build_deconv_net(latent_dim, n_upsampling_layers=4, filters=128, activation_out='sigmoid'):
    """
    Build a deconvolutional decoder network.
    """
    input = tf.keras.Input(shape=(latent_dim,))
    x = Dense(4 * 4 * filters * 8, activation='relu', name='dec_input')(input)
    x = Reshape((4, 4, filters * 8))(x)

    default_args = dict(kernel_size=(3, 3), strides=(2, 2), padding='same', activation='relu')

    # Add deconvolution layers to gradually enlarge the feature map to 64x64
    x = Conv2DTranspose(filters=filters * 4, **default_args)(x)  # 8x8x512
    x = Conv2DTranspose(filters=filters * 2, **default_args)(x)  # 16x16x256
    x = Conv2DTranspose(filters=filters, **default_args)(x)      # 32x32x128
    x = Conv2DTranspose(filters=filters // 2, **default_args)(x) # 64x64x64

    # fixed layers
    x = Conv2D(filters=3, kernel_size=(3, 3), padding='same', activation=activation_out, name='dec_output')(x)

    model = tf.keras.Model(inputs=input, outputs=x, name='Decoder')

    model.summary()
    return model

"""### Convolutional Autoencoder example

Using these two basic building blocks we can now build a Convolutional Autoencoder (CAE).

<img src="https://lilianweng.github.io/lil-log/assets/images/autoencoder-architecture.png" width="500">



Even though it's not a generative model, CAE is a great way to illustrate how these two components (convolutional and deconvolutional networks) can be used together to reconstruct images.

You can view such model as a compression/dimensionality reduction method as each image gets compressed to a vector of 256 numbers by the encoder and gets decompressed back into an image using the decoder network.
"""

def build_convolutional_autoencoder(data_shape, latent_dim, filters=128):
    encoder = build_conv_net(data_shape, latent_dim, n_downsampling_layers=6, filters=filters)
    decoder = build_deconv_net(latent_dim, n_upsampling_layers=6, filters=filters, activation_out='sigmoid')

    # We connect encoder and decoder into a single model
    autoencoder = tf.keras.Model(inputs=encoder.input, outputs=decoder(encoder.output))
    autoencoder.compile(optimizer='adam', loss='mse')

    return autoencoder



# Defining the model dimensions and building it
latent_dim = 256
filters = 128
cae = build_convolutional_autoencoder(data_shape=(64, 64, 3), latent_dim=latent_dim, filters=filters)



## Training the Convolutional autoencoder to reconstruct images
for epoch in range(50):
    print('\nEpoch: ', epoch)

    # Note that (X=y) when training autoencoders!
    # In this case we only care about qualitative performance, we don't split into train/test sets
    cae.fit(x=dataset, y=dataset, epochs=1, batch_size=64, verbose=1)

    samples = dataset[:9]
    reconstructed = cae.predict(samples)
    grid_plot(samples, name=f'Original (Epoch {epoch})', n=3, save=False)
    grid_plot(reconstructed, name=f'Reconstructed (Epoch {epoch})', n=3, save=False)

"""*Note: You may experiment with the latent dimensionality and number of filters in your convolutional network to see how it affects the reconstruction quality. Remember that this also affects the size of the model and time it takes to train.*

---
---


## 2. 2. Variational Autoencoders (VAEs)


#### Our Improvements

1. Latent Space Visualization Function: Randomly generate two points from the latent space,
and perform linear interpolation between the two points to generate multiple sets of latent
variables. Finally, use the decoder to decode these latent variables into images to demonstrate
the linear interpolation effect of the latent space;
2. The loss function uses mean square error (MSE) instead of the original Binary Crossentropy
to reconstruct the global image structure;
3. Customize the KLLossLayer, dynamically adjust the weight kl weight of the KL loss, and
gradually increase the importance of KL with the number of training rounds;
4. Adjust the laten dim, filters, and epochs parameters to achieve the best results
"""

class Sampling(tf.keras.layers.Layer):
    """
    Custom layer for the variational autoencoder
    It takes two vectors as input - one for means and other for variances of the latent variables described by a multimodal gaussian
    Its output is a latent vector randomly sampled from this distribution
    """
    def call(self, inputs):
        z_mean, z_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_var) * epsilon

def build_vae(data_shape, latent_dim, filters=128):

    # Building the encoder - starts with a simple downsampling convolutional network
    encoder = build_conv_net(data_shape, latent_dim * 2, n_downsampling_layers=6, filters=filters)

    # Adding special sampling layer that uses the reparametrization trick
    z_mean = Dense(latent_dim, name='z_mean')(encoder.output)
    z_var = Dense(latent_dim, name='z_var')(encoder.output)
    z = Sampling()([z_mean, z_var])

    # Connecting the two encoder parts
    encoder = tf.keras.Model(inputs=encoder.input, outputs=z)

    # Defining the decoder which is a regular upsampling deconvolutional network
    decoder = build_deconv_net(latent_dim, activation_out='sigmoid', filters=filters)
    vae = tf.keras.Model(inputs=encoder.input, outputs=decoder(z))

    # Define a custom layer for the KL loss calculation
    class KLLossLayer(tf.keras.layers.Layer):
        def call(self, inputs):
            z_mean, z_var = inputs
            kl_loss = -0.5 * tf.reduce_sum(z_var - tf.square(z_mean) - tf.exp(z_var) + 1)
            # Add the KL loss to the model's losses
            self.add_loss(kl_loss / tf.cast(tf.keras.backend.prod(data_shape), tf.float32))
            return inputs  # Pass through the inputs unchanged

    # Apply the custom layer to z_mean and z_var
    _, _ = KLLossLayer()([z_mean, z_var])

    vae.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4), loss='mse')

    return encoder, decoder, vae

"""Latent Space Visualization Function"""

def visualize_latent_space(decoder, latent_dim, interpolation_steps=9):
    """
    Visualizes latent space interpolation
    """
    # Generate two random points as the start and end points of the interpolation
    z_start = np.random.randn(latent_dim)
    z_end = np.random.randn(latent_dim)

    # Linear interpolation of latent space
    interpolation = np.linspace(z_start, z_end, interpolation_steps)
    interpolated_images = decoder(interpolation)

    n = int(np.ceil(np.sqrt(interpolation_steps)))
    grid_plot(interpolated_images, name='Latent Space Interpolation', n=n, save=False)

"""Better training effects can be obtained by adjusting the latent_dim, epochs, learning_rate and batch_size."""

latent_dim = 256
filters = 128


class KLLossLayer(tf.keras.layers.Layer):
    def call(self, inputs):
        z_mean, z_var = inputs
        kl_loss = -0.5 * tf.reduce_sum(1 + z_var - tf.square(z_mean) - tf.exp(z_var), axis=-1)
        kl_weight = tf.keras.backend.get_value(self.kl_weight)
        self.add_loss(kl_weight * tf.reduce_mean(kl_loss))
        return inputs

    def set_kl_weight(self, weight):
        self.kl_weight = tf.Variable(weight, trainable=False)

kl_layer = KLLossLayer()
kl_layer.set_kl_weight(0.0)

# Build VAE Model
encoder, decoder, vae = build_vae(dataset.shape[1:], latent_dim, filters=filters)

# Train VAE
for epoch in range(50):  # epochs
    print(f"Epoch {epoch + 1}")
    kl_layer.set_kl_weight(min(1.0, epoch / 10.0))  # Dynamically adjust KL weights
    vae.fit(x=dataset, y=dataset, epochs=1, batch_size=32, verbose=1)

    # Visualization
    latent_vectors = np.random.randn(9, latent_dim)
    generated_images = decoder(latent_vectors).numpy()
    grid_plot(np.clip(generated_images, 0, 1), name=f'VAE Generated Images (Epoch {epoch + 1})', n=3, save=False)

    if (epoch + 1) % 10 == 0:
        visualize_latent_space(decoder, latent_dim, interpolation_steps=9)

"""---

## 2.3 Generative Adversarial Networks (GANs)

### Our Improvements

1. Generator is based on the improved decoder implementation, with deeper layers and larger
potential dimensions(default 256);
2. The optimizer uses a reduced learning rate for better GAN training;
3. The discriminator freezes parameters when training GAN while dynamically adjust the
generator and discriminator weights to prevent training instability;
4. Adjust the laten dim, filters, and epochs parameters to achieve the best results
"""

def build_gan(data_shape, latent_dim, filters=128, lr=0.0001, beta_1=0.5):
    """
    Constructs the GAN: Generator, Discriminator, and Combined Model
    """
    optimizer = Adam(learning_rate=lr, beta_1=beta_1)

    # Build the generator
    generator = build_deconv_net(latent_dim, activation_out='tanh', filters=filters)

    # Build the discriminator
    discriminator = build_conv_net(data_shape, out_shape=1, filters=filters)
    discriminator.compile(loss='binary_crossentropy', optimizer=optimizer)

    # Freeze discriminator weights when training the GAN
    discriminator.trainable = False
    gan_output = discriminator(generator.output)
    gan = tf.keras.Model(inputs=generator.input, outputs=gan_output)
    gan.compile(loss='binary_crossentropy', optimizer=optimizer)

    return discriminator, generator, gan


def get_batch(generator, dataset, batch_size=64):
    """
    Prepares real and fake batches for discriminator training
    """
    half_batch = batch_size // 2

    # Generate fake images
    latent_vectors = tf.random.normal(shape=(half_batch, latent_dim))
    fake_data = generator(latent_vectors, training=False)

    # Select random real images
    idx = np.random.randint(0, dataset.shape[0], half_batch)
    real_data = dataset[idx]

    # Combine fake and real data
    X = tf.concat([real_data, fake_data], axis=0)
    y = tf.concat([tf.ones((half_batch, 1)), tf.zeros((half_batch, 1))], axis=0)

    return X, y


def train_gan(generator, discriminator, gan, dataset, latent_dim, n_epochs=20, batch_size=64):
    """
    GAN training loop
    """
    batches_per_epoch = dataset.shape[0] // batch_size

    for epoch in range(n_epochs):
        print(f"Epoch {epoch + 1}/{n_epochs}")
        for _ in tqdm(range(batches_per_epoch)):
            # Train the discriminator
            X, y = get_batch(generator, dataset, batch_size)
            discriminator_loss = discriminator.train_on_batch(X, y)

            # Train the generator
            latent_vectors = tf.random.normal(shape=(batch_size, latent_dim))
            y_gan = tf.ones((batch_size, 1))
            generator_loss = gan.train_on_batch(latent_vectors, y_gan)

        # Visualize generated images at the end of each epoch
        noise = tf.random.normal(shape=(16, latent_dim))
        generated_images = generator(noise, training=False).numpy()
        grid_plot(generated_images, name=f"Generated Images (Epoch {epoch + 1})", n=3)

"""Again, Better training effects can be obtained by adjusting the latent_dim, epochs, learning_rate and batch_size."""

# Training the GAN
latent_dim = 128
filters = 128

# Load the dataset
dataset_scaled = load_real_samples(file_path='/content/drive/MyDrive/Dataset/preprocessed_data.npy', scale=True)

# Build the GAN
discriminator, generator, gan = build_gan(data_shape=(64, 64, 3), latent_dim=latent_dim, filters=128, lr=0.0001)

# Train the GAN
train_gan(generator, discriminator, gan, dataset_scaled, latent_dim, n_epochs=50, batch_size=64)